
resolver 127.0.0.11 valid=30s ipv6=off;

server {
    listen 80;
    server_name _;

    location / {
        root        /usr/share/nginx/html;
        index       index.html;
        try_files   $uri $uri/ /index.html;
    }
}
