name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull frontend image
        run: docker pull limseongin/paw-frontend:2.0

      - name: Pull backend image
        run: docker pull limseongin/paw-backend:3.0

      - name: Show files
        run: ls -al

      - name: Check containers
        run: docker ps
